bug fixes

diff --git a/lofi-cli b/lofi-cli
--- a/lofi-cli
+++ b/lofi-cli
@@ -1,28 +1,41 @@
 #!/bin/bash
 
-# Define associative arrays to store custom URLs and their names
+is_playback_stopped=true  
+keep_running=true
 declare -A custom_urls
 
-# Flag to track if playback has been stopped
-stopped=false
+play_audio() {
+  local url=$1
 
-# Flag to track whether to display the options menu
-show_options=true
+  if ! $is_playback_stopped; then
+    stop_playback
+  fi
 
-# Function to stop playback
+  mpv "$url" --no-video --really-quiet & disown
+  keep_running=false
+  echo "Playback Started."
+}
+
 stop_playback() {
   pkill -f "mpv"
   echo "Playback stopped."
-  stopped=true
+  is_playback_stopped=true
+}
+
+
+exit_script() {
+  echo "Goodbye!"
+  exit 0
 }
 
 if [[ "$1" == "-s" ]]; then
-  # If the script is run with "-s" option, stop the playback and exit
   stop_playback
   show_options=false
+  exit_script
 fi
 
-while $show_options; do
+while $keep_running; do
+
   echo "Choose an option:"
   echo "1. Play lofi"
   echo "2. Play whiteNoise"
@@ -31,92 +44,77 @@ while $show_options; do
   echo "5. Manage custom videos"
   echo "6. Stop current playback"
   echo "7. Quit"
+
   read -p "Enter your choice: " choice
 
   case "$choice" in
     1)
-      if ! $stopped; then
-        stop_playback
-      fi
-      mpv "https://www.youtube.com/watch?v=jfKfPfyJRdk" --no-video --really-quiet & disown
+      play_audio "https://www.youtube.com/watch?v=jfKfPfyJRdk"
       ;;
+
     2)
-      if ! $stopped; then
-        stop_playback
-      fi
-      mpv "https://www.youtube.com/watch?v=vLEek3I3wac" --no-video --really-quiet & disown
+      play_audio "https://www.youtube.com/watch?v=vLEek3I3wac"
       ;;
+
     3)
-      if ! $stopped; then
-        stop_playback
-      fi
-      mpv "https://www.youtube.com/watch?v=38LMlhYiQzc" --no-video --really-quiet & disown
+      play_audio "https://www.youtube.com/watch?v=38LMlhYiQzc"
       ;;
+
     4)
-      if ! $stopped; then
-        stop_playback
-      fi
-      mpv "https://www.youtube.com/watch?v=3ozXFWpFYzg" --no-video --really-quiet & disown
+      play_audio "https://www.youtube.com/watch?v=3ozXFWpFYzg"
       ;;
+
     5)
       while true; do
         echo "Manage custom videos:"
         echo "1. Play custom video"
-        echo "2. List saved custom videos"
-        echo "3. Play saved custom video"
+        echo "2. List saved videos"
+        echo "3. Play saved video"
         echo "4. Back to main menu"
+
         read -p "Enter your choice: " custom_choice
 
         case "$custom_choice" in
           1)
-            if ! $stopped; then
-              stop_playback
-            fi
-            read -p "Enter the YouTube URL to play: " custom_url
-            read -p "Enter a custom name for this URL: " custom_name
-            mpv "$custom_url" --no-video --really-quiet & disown
-            custom_urls["$custom_name"]=$custom_url
+            read -p "Enter YouTube URL: " url
+            read -p "Enter custom name: " name
+            play_audio "$url"
+            custom_urls["$name"]="$url"
             ;;
           2)
-            echo "Saved custom videos:"
-            for name in "${!custom_urls[@]}"; do
-              echo "$name: ${custom_urls[$name]}"
+            echo "Saved videos:"
+            for key in "${!custom_urls[@]}"; do
+              echo "$key: ${custom_urls[$key]}"
             done
             ;;
           3)
-            echo "Saved custom videos:"
-            for name in "${!custom_urls[@]}"; do
-              echo "$name: ${custom_urls[$name]}"
-            done
-            read -p "Enter the custom name to play: " custom_name
-            custom_url="${custom_urls[$custom_name]}"
-            if [ -n "$custom_url" ]; then
-              if ! $stopped; then
-                stop_playback
-              fi
-              mpv "$custom_url" --no-video --really-quiet & disown
+            read -p "Enter custom name to play: " name
+            if [ -n "${custom_urls[$name]}" ]; then
+              play_audio "${custom_urls[$name]}"
             else
-              echo "Custom name not found."
+              echo "Custom video not found."
             fi
             ;;
           4)
             break
             ;;
           *)
-            echo "Invalid option. Please choose a valid option."
-            ;;
+            echo "Invalid choice"
         esac
       done
       ;;
+
     6)
       stop_playback
       ;;
+
     7)
-      echo "Goodbye!"
-      exit 0
+      keep_running=false
+      exit_script
       ;;
+
     *)
-      echo "Invalid option. Please choose a valid option."
+      echo "Invalid choice"
       ;;
   esac
 done
